# Generated by Django 5.2.2 on 2025-06-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion_muchos_muchos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
